[package]
name = "divvysim"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.29"
rust_decimal_macros = "1.29"
rayon = "1.6.1"
log = "0.4"
env_logger = "0.10.0"

[development]
prompt = "1.0.0"
